theme = "terminimal"

# The URL the site will be built for
base_url = "https://tmpvec.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

generate_feeds = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here

# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "pink"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "orange"

# The logo text - defaults to 2 non-breaking spaces.
logo_text = "tmpvec"

# The logo link - defaults to base_url.
logo_home_link = "/about"

menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    { name = "about me", url = "$BASE_URL/about" },
    { name = "blog", url = "$BASE_URL/blog" },

    # Duplicate
    # { name = "archive", url = "$BASE_URL/archive" },

    # set newtab to true to make the link open in new tab
    #{ name = "github", url = "https://github.com/tmpvec", newtab = true },
    { name = "projects", url = "$BASE_URL/projects" },
    { name = "contact", url = "$BASE_URL/contact" },
]

# Whether to show links to earlier and later posts
# on each post page.
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "tmpvec"

# Copyright text in HTML format. If specified,
# entirely replaces default copyright and author.
copyright_html = "© 2025 tmpvec :: made with&nbsp;<a href=\"https://github.com/pawroman/zola-theme-terminimal\">terminimal</a> &&&nbsp;<a href=\"https://github.com/getzola/zola\">Zola</a>"
